### ISSUE TITLE
matplotlib.font_manager._rebuild() deprecated

### ISSUE THREAD

**Issue by PeterMakus** [PeterMakus/PyGLImER#37]
@lsawade 
You use this function in plot.plot_utils_set_mpl_params() (this function exists twice - once in src and once in examples). I don't really know what it did, but now it doesn't exist anymore. In general, it's probably always a good idea to not use private functions as they might suddenly be deprecated.
Right now, I just commented the two lines. Can you check whether the plots look the way they should? (I don't notice a difference, but as it was you who coded it, maybe it's good if you look over it)
If it's alright, you can close this issue. Else you will maybe have to find a different way to do what this function did.
Cheers,
Peter

**Comment by lsawade** [comment]
This was an issue with Matplotlib building the fontmanager once with system fonts, and then disregarding new additions. Since this is deprecated, I assume that it "just" works now and rebuilding isn't necessary. I have too many unfinished changes on my end right now to just pull into push into the master branch. My hunch is that it is removable.

Also, I was thinking about changing the rc_params, to make the figures look more journal like. All the figures that I have recently sent you contain this change, but I have not made this change in PyGLImER. I would go through all the plots and check whether they look fine. What do you think?

**Comment by PeterMakus** [comment]
Alright! I will close it for now. In case that it is an actual issue, it can just be reopened
